#!/usr/bin/env bash
#
# Installs this repository's skills where agents look for them, and, on request,
# the agent roles that chain them.
#
#   ./install.sh                          # user scope, every detected client
#   ./install.sh --scope project --into ~/projects/my-app
#   ./install.sh --client claude --copy
#   ./install.sh --client claude --with-agents
#
# Symlinks by default: repository updates are picked up without reinstalling.
# `--copy` produces independent copies.
set -euo pipefail

REPOSITORY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE="$REPOSITORY/skills"
AGENTS_SOURCE="$REPOSITORY/agents"
SCOPE="user"
CLIENT="auto"
TARGET=""
MODE="symlink"
WITH_AGENTS="no"

# First line of every file this script generates. It is how the script tells its
# own output from someone else's file: only the former is ever overwritten.
GENERATED_MARKER="# Generated by proof-over-vibes install.sh"

usage() {
  cat <<'USAGE'
Usage: ./install.sh [options]

  --scope user|project   Scope. `user` installs for you on this machine;
                         `project` installs into one repository (default: user).
  --into <path>          Project root. Required with --scope project.
  --client <name>        agents | claude | codex | gemini | all (default: auto).
  --with-agents          Also install the agent roles (agents/) for the clients
                         that have a subagent format: claude, codex, gemini.
                         Off by default: a role runs on its own, unasked, so it
                         is never installed unasked.
  --copy                 Copy instead of creating symlinks.
  -h, --help             This help.

Skill directories:

  agents   ~/.agents/skills/        or  <project>/.agents/skills/
           The interoperable directory, read by Codex, Cursor, Gemini CLI,
           Copilot and other clients conforming to the specification.
  claude   ~/.claude/skills/        or  <project>/.claude/skills/
           Claude Code, which kept its own directory.
  codex, gemini
           Both read the interoperable directory: they install into agents.

Agent role directories (with --with-agents):

  claude   .claude/agents/<role>.md      linked or copied
  gemini   .gemini/agents/<role>.md      linked or copied
  codex    .codex/agents/<role>.toml     always generated: Codex reads TOML,
                                         so a link cannot work. Run the script
                                         again to pick up repository updates.

Roles carry no model and no reasoning effort: each one inherits your session's.

`auto` installs for the clients whose directory (.agents, .claude, .codex,
.gemini) already exists, and falls back to `agents` if none is detected.
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --scope)       SCOPE="${2:?--scope expects a value}"; shift 2 ;;
    --into)        TARGET="${2:?--into expects a path}"; shift 2 ;;
    --client)      CLIENT="${2:?--client expects a value}"; shift 2 ;;
    --with-agents) WITH_AGENTS="yes"; shift ;;
    --copy)        MODE="copy"; shift ;;
    -h|--help)     usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

[ -d "$SOURCE" ] || { echo "No skills/ folder next to the script." >&2; exit 1; }
if [ "$WITH_AGENTS" = "yes" ]; then
  [ -d "$AGENTS_SOURCE" ] || { echo "No agents/ folder next to the script." >&2; exit 1; }
fi

case "$SCOPE" in
  user)    ROOT="$HOME" ;;
  project)
    [ -n "$TARGET" ] || { echo "--scope project requires --into <path>." >&2; exit 1; }
    [ -d "$TARGET" ] || { echo "Project not found: $TARGET" >&2; exit 1; }
    ROOT="$(cd "$TARGET" && pwd)" ;;
  *) echo "--scope expects 'user' or 'project'." >&2; exit 1 ;;
esac

# --- which clients -----------------------------------------------------------
# Detection: we never create a client directory the user does not use.
CLIENTS=()
case "$CLIENT" in
  agents|claude|codex|gemini) CLIENTS=("$CLIENT") ;;
  all)  CLIENTS=(agents claude codex gemini) ;;
  auto)
    [ -d "$ROOT/.agents" ] && CLIENTS+=(agents)
    [ -d "$ROOT/.claude" ] && CLIENTS+=(claude)
    [ -d "$ROOT/.codex" ]  && CLIENTS+=(codex)
    [ -d "$ROOT/.gemini" ] && CLIENTS+=(gemini)
    [ ${#CLIENTS[@]} -eq 0 ] && CLIENTS=(agents)
    ;;
  *) echo "--client expects 'agents', 'claude', 'codex', 'gemini', 'all' or 'auto'." >&2; exit 1 ;;
esac

contains() {  # contains <value> <list...>
  local needle="$1"; shift
  local item
  for item in "$@"; do [ "$item" = "$needle" ] && return 0; done
  return 1
}

SKILL_DESTINATIONS=()
CLAUDE_AGENTS=""
GEMINI_AGENTS=""
CODEX_AGENTS=""

for client in "${CLIENTS[@]}"; do
  case "$client" in
    claude) skills="$ROOT/.claude/skills" ;;
    *)      skills="$ROOT/.agents/skills" ;;
  esac
  if [ ${#SKILL_DESTINATIONS[@]} -eq 0 ] || ! contains "$skills" "${SKILL_DESTINATIONS[@]}"; then
    SKILL_DESTINATIONS+=("$skills")
  fi
  case "$client" in
    claude) CLAUDE_AGENTS="$ROOT/.claude/agents" ;;
    gemini) GEMINI_AGENTS="$ROOT/.gemini/agents" ;;
    codex)  CODEX_AGENTS="$ROOT/.codex/agents" ;;
  esac
done

echo "Source      : $SOURCE"
echo "Mode        : $MODE"
printf 'Skills into : %s\n' "${SKILL_DESTINATIONS[@]}"
if [ "$WITH_AGENTS" = "yes" ]; then
  echo "Agents from : $AGENTS_SOURCE"
  for destination in "$CLAUDE_AGENTS" "$GEMINI_AGENTS" "$CODEX_AGENTS"; do
    [ -n "$destination" ] && echo "Agents into : $destination"
  done
  if [ -z "$CLAUDE_AGENTS$GEMINI_AGENTS$CODEX_AGENTS" ]; then
    echo "Agents into : (none: the selected clients have no subagent format here)"
  fi
fi
echo

# --- skills ------------------------------------------------------------------
for destination in "${SKILL_DESTINATIONS[@]}"; do
  mkdir -p "$destination"

  # A renamed or removed skill leaves a dangling symlink behind. We only clear
  # links that point into this repository — someone else's skills are theirs.
  for link in "$destination"/*; do
    [ -L "$link" ] || continue
    [ -e "$link" ] && continue
    case "$(readlink "$link")" in
      "$SOURCE"/*) rm -f "$link"; echo "  - $(basename "$link") (dangling link removed)" ;;
    esac
  done

  for skill in "$SOURCE"/*/; do
    name="$(basename "$skill")"
    link="$destination/$name"

    # A pre-existing skill that is not ours: never overwritten silently.
    if [ -e "$link" ] && [ ! -L "$link" ]; then
      echo "  ~ $name already in $destination (a copy, not a link) — skipped"
      continue
    fi

    rm -f "$link"
    if [ "$MODE" = "symlink" ]; then
      ln -s "${skill%/}" "$link"
    else
      cp -R "${skill%/}" "$link"
    fi
    echo "  + $name"
  done
done

# --- agent roles -------------------------------------------------------------
# Claude Code and Gemini CLI read the same shape: markdown, a frontmatter with
# `name` and `description`, the prompt as the body. The source file is already
# in that shape, so it is linked or copied as is.
install_markdown_agents() {  # install_markdown_agents <destination>
  local destination="$1" link file name
  mkdir -p "$destination"

  for link in "$destination"/*.md; do
    [ -L "$link" ] || continue
    [ -e "$link" ] && continue
    case "$(readlink "$link")" in
      "$AGENTS_SOURCE"/*) rm -f "$link"; echo "  - $(basename "$link") (dangling link removed)" ;;
    esac
  done

  for file in "$AGENTS_SOURCE"/*.md; do
    name="$(basename "$file")"
    link="$destination/$name"

    if [ -e "$link" ] && [ ! -L "$link" ]; then
      echo "  ~ $name already in $destination (a copy, not a link) — skipped"
      continue
    fi

    rm -f "$link"
    if [ "$MODE" = "symlink" ]; then
      ln -s "$file" "$link"
    else
      cp "$file" "$link"
    fi
    echo "  + $name"
  done
}

# Reads one frontmatter field of a role file. Only the first `---` pair counts:
# a later `---` in the body is a horizontal rule, not a delimiter.
frontmatter_field() {  # frontmatter_field <file> <field>
  awk -v field="$2" '
    /^---$/ && count < 2 { count++; next }
    count == 1 && index($0, field ":") == 1 {
      sub("^" field ":[ \t]*", ""); gsub(/^["'\'']|["'\'']$/, ""); print; exit
    }' "$1"
}

role_body() {  # role_body <file>
  awk '/^---$/ && count < 2 { count++; next } count >= 2' "$1"
}

# Codex reads one TOML file per agent. It cannot be a link: the file has to be
# built from the role's frontmatter and body, so it is regenerated on each run.
install_codex_agents() {  # install_codex_agents <destination>
  local destination="$1" file name description target source
  mkdir -p "$destination"

  # A generated file whose role no longer exists. Only our own output is cleared.
  for target in "$destination"/*.toml; do
    [ -f "$target" ] || continue
    [ "$(head -n 1 "$target")" = "$GENERATED_MARKER" ] || continue
    source="$(sed -n '2s/^# Source: \([^ ]*\).*/\1/p' "$target")"
    if [ -n "$source" ] && [ ! -f "$AGENTS_SOURCE/$source" ]; then
      rm -f "$target"; echo "  - $(basename "$target") (role removed)"
    fi
  done

  for file in "$AGENTS_SOURCE"/*.md; do
    # The name has to match across file and field; hyphens become underscores,
    # the form Codex's own examples use.
    name="$(frontmatter_field "$file" name | tr '-' '_')"
    description="$(frontmatter_field "$file" description | sed 's/\\/\\\\/g; s/"/\\"/g')"
    target="$destination/$name.toml"

    if [ -e "$target" ] && [ "$(head -n 1 "$target")" != "$GENERATED_MARKER" ]; then
      echo "  ~ $name.toml already in $destination (not generated by this script) — skipped"
      continue
    fi

    {
      echo "$GENERATED_MARKER"
      echo "# Source: $(basename "$file") — edit the role in the repository, then run the script again."
      echo "name = \"$name\""
      echo "description = \"$description\""
      echo "developer_instructions = '''"
      role_body "$file"
      echo "'''"
    } > "$target"
    echo "  + $name.toml"
  done
}

if [ "$WITH_AGENTS" = "yes" ]; then
  echo
  [ -n "$CLAUDE_AGENTS" ] && install_markdown_agents "$CLAUDE_AGENTS"
  [ -n "$GEMINI_AGENTS" ] && install_markdown_agents "$GEMINI_AGENTS"
  [ -n "$CODEX_AGENTS" ]  && install_codex_agents "$CODEX_AGENTS"
fi

echo
echo "Done. To verify:"
echo "    python3 tools/validate-skills.py --root ."
